
version: 2

models:
  - name: product_dim
    columns:
      - name: product_key
        tests:
          - unique
          - not_null

  - name: product_type_dim
    columns:
      - name: product_type_key
        tests:
          - unique
          - not_null

  - name: product_category_dim
    columns:
      - name: product_category_key
        tests:
          - unique
          - not_null

  - name: date
    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  - name: transaction_fact
    columns:
      - name: product_key
        tests:
          - relationships:
              to: ref('product_dim')
              field: product_key

      - name: product_type_key
        tests:
          - relationships:
              to: ref('product_type_dim')
              field: product_type_key

      - name: product_category_key
        tests:
          - relationships:
              to: ref('product_category_dim')
              field: product_category_key

      - name: date_key
        tests:
          - relationships:
              to: ref('date')
              field: date_key